import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: ['tests/unit/**/*.test.ts', 'tests/corpus/**/*.test.ts'],
    environment: 'node',
    coverage: {
      provider: 'v8',
      include: ['src/**/*.ts'],
      exclude: [
        // Entrypoint glue: wiring that only exists inside a live extension
        // (message ports, offscreen documents, DOM bootstrapping). Its logic
        // lives in lib/ and is covered there; the DOM behaviour it produces is
        // covered through the happy-dom converter suites.
        'src/entrypoints/**',
        // Generated by wxt.
        'src/**/*.d.ts',
        // Type-only modules. They compile to nothing, so v8 reports them as
        // 0% forever and no test can move that number.
        'src/**/types.ts',
      ],
      reporter: ['text', 'html'],
      // Not a target to drift toward — a gate. A line nobody executes is a
      // line nobody has checked.
      thresholds: {
        lines: 100,
        functions: 100,
        branches: 100,
        statements: 100,
      },
    },
  },
});
