import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    include: [
      'tests/unit/**/*.test.ts',
      'tests/corpus/**/*.test.ts',
      'tests/pages/**/*.test.ts',
    ],
    environment: 'node',
    coverage: {
      provider: 'v8',
      include: ['src/**/*.ts'],
      exclude: [
        // Entrypoint glue, and only glue: the `main()` of a page, the
        // background's message wiring, the offscreen bootstrap. What is left
        // after the logic has been pulled out is `document.getElementById`,
        // `addEventListener`, and calls into lib/ — testing it would test
        // happy-dom rather than this extension.
        //
        // Everything with a decision in it is NOT excluded and is held to the
        // same 100% as lib/: content/converter, content/detector,
        // content/observer, content/pay, content/state, content/markers, and
        // background/rates.
        'src/entrypoints/*/index.ts',
        'src/entrypoints/*/main.ts',
        'src/entrypoints/*.chrome/main.ts',
        'src/entrypoints/background/quick.ts',
        'src/entrypoints/background/alarms.ts',
        // Generated by wxt.
        'src/**/*.d.ts',
        // Type-only modules. They compile to nothing, so v8 reports them as
        // 0% forever and no test can move that number.
        'src/**/types.ts',
      ],
      // json feeds scripts/uncovered-branches.mjs: the text reporter lists
      // uncovered LINES, which says nothing about a file at 100% lines and 90%
      // branches — the line ran, one arm of it did not.
      reporter: ['text', 'html', 'json'],
      // Not a target to drift toward — a gate. A line nobody executes is a
      // line nobody has checked.
      thresholds: {
        lines: 100,
        functions: 100,
        branches: 100,
        statements: 100,
      },
    },
  },
});
