import type { Category, PracticeItem } from './types';

/**
 * Everyday things people already hold a price for.
 *
 * A practice question only works if the user knows the fiat side of it already.
 * "How much is 0.17 ZEC?" is unanswerable; "how many ZEC is a haircut?" binds a
 * ZEC quantity to a number they can already picture, and that binding is the
 * entire mechanism. So the selection rule is *widely-known price*, not
 * *interesting object* — an obscure item turns the question into trivia about
 * the thing and teaches nothing about the unit.
 *
 * Three properties are load-bearing, and each is pinned by
 * tests/unit/practice.catalogue.test.ts:
 *
 * - **Spread across magnitudes.** A catalogue clumped at $10-100 trains one
 *   band and leaves the user guessing wildly at both a bus fare and a year of
 *   rent. Every band in `bandOf` has to be reachable at a realistic rate, so
 *   the list runs from a $0.35 photo print to a $58,000 year of tuition, with
 *   each order of magnitude in between carrying real weight.
 * - **Every category populated.** The modes filter by category, and a category
 *   with two entries repeats them until the user is memorising the list rather
 *   than estimating.
 * - **Stable ids.** Per-item progress is keyed on the id, so renaming one
 *   silently discards the history behind it. Ids are kebab-case and never
 *   recycled for a different thing.
 *
 * Prices are typical US retail and deliberately not rounded to powers of ten.
 * A catalogue of $10 / $100 / $1000 items lets someone pattern-match the answer
 * off the shape of the number instead of estimating it.
 */

/**
 * The compact source form: id, label, emoji, amount, category.
 *
 * The two constant fields are filled in below rather than repeated 300-odd
 * times. Written out in full, every entry wraps across several lines at the
 * 100-column limit, and a list nobody can scan is a list where a duplicate id
 * or a misfiled category hides in plain sight.
 */
type Entry = [id: string, label: string, emoji: string, amount: number, category: Category];

const ENTRIES: Entry[] = [
  // drink
  ['milk-pint', 'a pint of milk', '🥛', 1.85, 'drink'],
  ['soda-can', 'a can of soda', '🥤', 2.25, 'drink'],
  ['water-bottle', 'a bottle of water', '💧', 2.5, 'drink'],
  ['coffee-drip', 'a cup of drip coffee', '☕', 2.95, 'drink'],
  ['espresso', 'a shot of espresso', '☕', 3.25, 'drink'],
  ['tea-cup', 'a cup of tea', '🍵', 3.5, 'drink'],
  ['iced-coffee', 'a canned iced coffee', '🧊', 3.75, 'drink'],
  ['energy-drink', 'an energy drink', '⚡', 3.99, 'drink'],
  ['juice-carton', 'a carton of orange juice', '🧃', 4.99, 'drink'],
  ['latte', 'a latte', '☕', 5.75, 'drink'],
  ['bubble-tea', 'a bubble tea', '🧋', 6.5, 'drink'],
  ['smoothie', 'a smoothie', '🥤', 7.5, 'drink'],
  ['beer-pint', 'a pint of beer', '🍺', 8.5, 'drink'],
  ['wine-glass', 'a glass of house wine', '🍷', 12, 'drink'],
  ['wine-bottle', 'a bottle of supermarket wine', '🍾', 13.99, 'drink'],
  ['beer-sixpack', 'a six-pack of craft beer', '🍺', 14, 'drink'],
  ['cocktail', 'a cocktail', '🍸', 16, 'drink'],
  ['coffee-beans', 'a bag of specialty coffee beans', '☕', 22, 'drink'],
  ['beer-case', 'a case of beer', '🍺', 34, 'drink'],
  ['whisky-bottle', 'a bottle of good whisky', '🥃', 45, 'drink'],
  ['champagne', 'a bottle of champagne', '🍾', 55, 'drink'],
  ['coffee-month', 'a month of daily coffees', '☕', 90, 'drink'],
  ['espresso-machine', 'an espresso machine', '☕', 240, 'drink'],
  ['wine-case', 'a case of fine wine', '🍷', 480, 'drink'],
  ['coffee-year', 'a year of daily coffees', '☕', 1080, 'drink'],
  ['espresso-machine-pro', 'a commercial espresso machine', '☕', 8500, 'drink'],
  ['wine-cellar', 'a stocked wine cellar', '🍷', 14000, 'drink'],

  // food
  ['banana', 'a banana', '🍌', 0.65, 'food'],
  ['apple', 'an apple', '🍎', 1.1, 'food'],
  ['candy-bar', 'a candy bar', '🍫', 2.15, 'food'],
  ['doughnut', 'a doughnut', '🍩', 2.75, 'food'],
  ['bread-loaf', 'a loaf of bread', '🍞', 3.49, 'food'],
  ['taco', 'a taco', '🌮', 3.5, 'food'],
  ['milk-gallon', 'a gallon of milk', '🥛', 4.1, 'food'],
  ['eggs-dozen', 'a dozen eggs', '🥚', 4.25, 'food'],
  ['bagel', 'a bagel with cream cheese', '🥯', 4.5, 'food'],
  ['crisps-bag', 'a bag of chips', '🥔', 4.99, 'food'],
  ['cereal-box', 'a box of cereal', '🥣', 5.75, 'food'],
  ['ground-beef', 'a pound of ground beef', '🥩', 6.5, 'food'],
  ['rotisserie-chicken', 'a rotisserie chicken', '🍗', 8.99, 'food'],
  ['fast-food-meal', 'a fast-food combo meal', '🍔', 11.5, 'food'],
  ['burrito', 'a burrito', '🌯', 12, 'food'],
  ['deli-sandwich', 'a sandwich from a deli', '🥪', 13.5, 'food'],
  ['pizza-large', 'a large pizza', '🍕', 21, 'food'],
  ['birthday-cake', 'a birthday cake', '🎂', 48, 'food'],
  ['dinner-for-two', 'a dinner for two', '🍽️', 85, 'food'],
  ['groceries-week', 'a week of groceries for one', '🛒', 95, 'food'],
  ['tasting-menu', 'a tasting menu for one', '🍽️', 195, 'food'],
  ['groceries-month', 'a month of groceries for one', '🛒', 420, 'food'],
  ['school-lunches-year', 'a year of school lunches', '🍱', 900, 'food'],
  ['catering-party', 'a catered party for twenty', '🍽️', 950, 'food'],
  ['groceries-month-family', 'a month of groceries for a family', '🛒', 1250, 'food'],
  ['freezer-stocked', 'a freezer stocked with meat', '🥩', 2200, 'food'],
  ['groceries-year-family', 'a year of groceries for a family', '🛒', 15000, 'food'],

  // transport
  ['bus-fare', 'a bus fare', '🚌', 2.9, 'transport'],
  ['subway-ride', 'a subway ride', '🚇', 2.9, 'transport'],
  ['petrol-gallon', 'a gallon of gas', '⛽', 3.45, 'transport'],
  ['parking-hour', 'an hour at a parking meter', '🅿️', 3.5, 'transport'],
  ['bike-tube', 'a bicycle inner tube', '🚲', 7.5, 'transport'],
  ['rideshare-short', 'a short rideshare', '🚕', 14, 'transport'],
  ['car-wash', 'a car wash', '🧼', 22, 'transport'],
  ['taxi-cross-town', 'a taxi across town', '🚖', 26, 'transport'],
  ['wipers', 'a set of windshield wipers', '🚗', 34, 'transport'],
  ['bike-helmet', 'a bicycle helmet', '🪖', 55, 'transport'],
  ['fuel-tank', 'a tank of fuel', '⛽', 62, 'transport'],
  ['oil-change', 'an oil change', '🛢️', 65, 'transport'],
  ['transit-pass-month', 'a monthly transit pass', '🎫', 82, 'transport'],
  ['car-insurance-month', 'a month of car insurance', '🚗', 165, 'transport'],
  ['car-battery', 'a car battery', '🔋', 185, 'transport'],
  ['parking-month', 'a month of downtown parking', '🅿️', 260, 'transport'],
  ['scooter', 'an electric scooter', '🛴', 340, 'transport'],
  ['bike-commuter', 'a commuter bicycle', '🚲', 480, 'transport'],
  ['tyres-set', 'a set of tires', '🛞', 720, 'transport'],
  ['e-bike', 'an e-bike', '🚲', 1900, 'transport'],
  ['car-insurance-year', 'a year of car insurance', '🚗', 1980, 'transport'],
  ['bike-road', 'a road bicycle', '🚴', 2600, 'transport'],
  ['transmission-repair', 'a transmission repair', '🔧', 3800, 'transport'],
  ['motorcycle-used', 'a used motorcycle', '🏍️', 4200, 'transport'],
  ['car-used', 'a used car', '🚗', 12000, 'transport'],
  ['car-new', 'a new sedan', '🚙', 34000, 'transport'],
  ['car-electric', 'an electric car', '🔌', 45000, 'transport'],

  // clothing
  ['shoelaces', 'a pair of shoelaces', '👟', 4, 'clothing'],
  ['socks', 'a pair of socks', '🧦', 4.5, 'clothing'],
  ['gloves', 'a pair of cotton gloves', '🧤', 6.5, 'clothing'],
  ['flip-flops', 'a pair of flip-flops', '🩴', 12, 'clothing'],
  ['beanie', 'a knit beanie', '🧢', 16, 'clothing'],
  ['t-shirt', 'a plain t-shirt', '👕', 22, 'clothing'],
  ['sunglasses', 'a pair of sunglasses', '🕶️', 25, 'clothing'],
  ['baseball-cap', 'a baseball cap', '🧢', 28, 'clothing'],
  ['necktie', 'a necktie', '👔', 42, 'clothing'],
  ['swimsuit', 'a swimsuit', '🩱', 45, 'clothing'],
  ['dress-shirt', 'a dress shirt', '👔', 55, 'clothing'],
  ['hoodie', 'a hoodie', '🧥', 62, 'clothing'],
  ['jeans', 'a pair of jeans', '👖', 68, 'clothing'],
  ['sneakers', 'a pair of sneakers', '👟', 85, 'clothing'],
  ['rain-jacket', 'a rain jacket', '🧥', 120, 'clothing'],
  ['running-shoes', 'a pair of running shoes', '👟', 135, 'clothing'],
  ['dress-shoes', 'a pair of dress shoes', '👞', 180, 'clothing'],
  ['wristwatch', 'a wristwatch', '⌚', 220, 'clothing'],
  ['winter-coat', 'a winter coat', '🧥', 260, 'clothing'],
  ['leather-boots', 'a pair of leather boots', '🥾', 290, 'clothing'],
  ['handbag', 'a handbag', '👜', 320, 'clothing'],
  ['gown', 'a formal gown', '👗', 480, 'clothing'],
  ['suit-wool', 'a wool suit', '🤵', 640, 'clothing'],
  ['suit-tailored', 'a tailored suit', '🤵', 1400, 'clothing'],
  ['wedding-dress', 'a wedding dress', '👰', 1900, 'clothing'],
  ['handbag-designer', 'a designer handbag', '👜', 2400, 'clothing'],
  ['watch-luxury', 'a luxury watch', '⌚', 6800, 'clothing'],
  ['wardrobe-designer', 'a designer wardrobe', '👗', 12000, 'clothing'],

  // tech
  ['cloud-storage-month', 'a month of cloud storage', '☁️', 2.99, 'tech'],
  ['mobile-game', 'a mobile game', '🎮', 4.99, 'tech'],
  ['batteries-pack', 'a pack of batteries', '🔋', 6.25, 'tech'],
  ['charging-cable', 'a phone charging cable', '🔌', 7.5, 'tech'],
  ['usb-stick', 'a usb stick', '💾', 9.99, 'tech'],
  ['mouse', 'a wired mouse', '🖱️', 15, 'tech'],
  ['phone-case', 'a phone case', '📱', 19, 'tech'],
  ['webcam', 'a webcam', '📷', 58, 'tech'],
  ['smart-speaker', 'a smart speaker', '🔊', 88, 'tech'],
  ['hard-drive', 'an external hard drive', '💽', 95, 'tech'],
  ['keyboard-mechanical', 'a mechanical keyboard', '⌨️', 110, 'tech'],
  ['earbuds', 'a pair of earbuds', '🎧', 130, 'tech'],
  ['printer', 'a printer', '🖨️', 175, 'tech'],
  ['headphones', 'noise-cancelling headphones', '🎧', 350, 'tech'],
  ['tablet', 'a tablet', '📱', 380, 'tech'],
  ['smartwatch', 'a smartwatch', '⌚', 420, 'tech'],
  ['console', 'a games console', '🎮', 520, 'tech'],
  ['phone-midrange', 'a mid-range phone', '📱', 640, 'tech'],
  ['tv-65', 'a 65-inch television', '📺', 980, 'tech'],
  ['phone-flagship', 'a flagship phone', '📱', 1150, 'tech'],
  ['laptop', 'a laptop', '💻', 1450, 'tech'],
  ['desktop-gaming', 'a gaming desktop', '🖥️', 2400, 'tech'],
  ['camera-pro', 'a professional camera', '📷', 3200, 'tech'],
  ['workstation', 'a high-end workstation', '🖥️', 6500, 'tech'],
  ['home-cinema', 'a home cinema setup', '🎬', 8500, 'tech'],
  ['office-computers', 'an office of computers', '💻', 24000, 'tech'],
  ['server-rack', 'a server rack', '🗄️', 38000, 'tech'],

  // home
  ['soap-bar', 'a bar of soap', '🧼', 1.75, 'home'],
  ['paper-towels', 'a roll of paper towels', '🧻', 2.49, 'home'],
  ['sponges', 'a pack of sponges', '🧽', 3.5, 'home'],
  ['light-bulb', 'a light bulb', '💡', 4.25, 'home'],
  ['dish-soap', 'a bottle of dish soap', '🧴', 4.99, 'home'],
  ['dish-towels', 'a set of dish towels', '🧺', 12, 'home'],
  ['house-plant', 'a house plant', '🪴', 18, 'home'],
  ['picture-frame', 'a picture frame', '🖼️', 24, 'home'],
  ['toaster', 'a toaster', '🍞', 38, 'home'],
  ['frying-pan', 'a frying pan', '🍳', 45, 'home'],
  ['bed-sheets', 'a set of bed sheets', '🛏️', 65, 'home'],
  ['dining-chair', 'a dining chair', '🪑', 130, 'home'],
  ['microwave', 'a microwave', '🍲', 140, 'home'],
  ['vacuum', 'a vacuum cleaner', '🧹', 180, 'home'],
  ['bookshelf', 'a bookshelf', '📚', 190, 'home'],
  ['coffee-table', 'a coffee table', '🪑', 220, 'home'],
  ['mattress', 'a mattress', '🛏️', 720, 'home'],
  ['washing-machine', 'a washing machine', '🧺', 890, 'home'],
  ['sofa', 'a sofa', '🛋️', 1200, 'home'],
  ['fridge', 'a refrigerator', '🧊', 1650, 'home'],
  ['dining-set', 'a dining table and chairs', '🪑', 1800, 'home'],
  ['bedroom-furniture', 'a bedroom of furniture', '🛏️', 4200, 'home'],
  ['roof-new', 'a new roof', '🏚️', 14000, 'home'],
  ['bathroom-reno', 'a bathroom renovation', '🚿', 15000, 'home'],
  ['solar-panels', 'a set of solar panels', '☀️', 22000, 'home'],
  ['kitchen-reno', 'a kitchen renovation', '🍳', 28000, 'home'],
  ['furniture-house', 'a house full of furniture', '🛋️', 32000, 'home'],

  // leisure
  ['lottery-ticket', 'a lottery ticket', '🎟️', 2, 'leisure'],
  ['cards-deck', 'a deck of cards', '🃏', 5.5, 'leisure'],
  ['magazine', 'a magazine', '📰', 6.99, 'leisure'],
  ['paperback', 'a paperback', '📕', 13, 'leisure'],
  ['streaming-month', 'a month of streaming', '📺', 15.99, 'leisure'],
  ['cinema-ticket', 'a cinema ticket', '🎬', 16, 'leisure'],
  ['gym-day-pass', 'a day pass at a gym', '🏋️', 25, 'leisure'],
  ['board-game', 'a board game', '🎲', 35, 'leisure'],
  ['video-game', 'a video game', '🎮', 70, 'leisure'],
  ['museum-membership', 'a museum membership', '🎫', 85, 'leisure'],
  ['concert-ticket', 'a concert ticket', '🎤', 95, 'leisure'],
  ['football-ticket', 'a football game ticket', '🏈', 120, 'leisure'],
  ['theme-park-pass', 'a theme park day pass', '🎢', 145, 'leisure'],
  ['guitar', 'a guitar', '🎸', 420, 'leisure'],
  ['streaming-year', 'a year of streaming services', '📺', 480, 'leisure'],
  ['surfboard', 'a surfboard', '🏄', 580, 'leisure'],
  ['golf-clubs', 'a set of golf clubs', '⛳', 650, 'leisure'],
  ['kayak', 'a kayak', '🛶', 820, 'leisure'],
  ['ski-pass-season', 'a season ski pass', '⛷️', 950, 'leisure'],
  ['season-ticket', 'a season ticket for a team', '🏟️', 1600, 'leisure'],
  ['home-gym', 'a home gym', '🏋️', 3400, 'leisure'],
  ['piano-upright', 'an upright piano', '🎹', 4200, 'leisure'],
  ['hot-tub', 'a hot tub', '🛁', 8500, 'leisure'],
  ['sailboat-small', 'a small sailboat', '⛵', 18000, 'leisure'],
  ['home-theatre', 'a home theatre room', '🎬', 26000, 'leisure'],
  ['piano-grand', 'a grand piano', '🎹', 42000, 'leisure'],
  ['swimming-pool', 'a swimming pool', '🏊', 45000, 'leisure'],

  // services
  ['photo-print', 'a photo print', '🖼️', 0.35, 'services'],
  ['stamp', 'a postage stamp', '📮', 0.78, 'services'],
  ['locker-day', 'a locker for a day', '🔒', 5, 'services'],
  ['shoe-shine', 'a shoe shine', '👞', 7, 'services'],
  ['parcel-delivery', 'a package delivery', '📦', 12, 'services'],
  ['dry-cleaning', 'a dry cleaning load', '👔', 28, 'services'],
  ['haircut', 'a haircut', '💇', 35, 'services'],
  ['manicure', 'a manicure', '💅', 45, 'services'],
  ['cleaning-hour', 'an hour of house cleaning', '🧹', 48, 'services'],
  ['gym-month', 'a month of a gym membership', '🏋️', 52, 'services'],
  ['phone-plan-month', 'a month of phone service', '📱', 65, 'services'],
  ['internet-month', 'a month of internet', '📶', 82, 'services'],
  ['dog-groom', 'a dog groom', '🐕', 95, 'services'],
  ['passport-renewal', 'a passport renewal', '🛂', 165, 'services'],
  ['plumber-callout', "a plumber's call-out", '🔧', 195, 'services'],
  ['cleaner-month', 'a month of a cleaner', '🧹', 320, 'services'],
  ['lawyer-hour', "a lawyer's hour", '⚖️', 380, 'services'],
  ['electrician-day', "an electrician's day", '⚡', 480, 'services'],
  ['gym-year', 'a year of a gym membership', '🏋️', 620, 'services'],
  ['childcare-month', 'a month of childcare', '🧸', 1250, 'services'],
  ['movers-day', 'a day with a moving company', '📦', 1400, 'services'],
  ['photographer-day', 'a photographer for a day', '📷', 2200, 'services'],
  ['wedding-photographer', 'a wedding photographer', '📸', 3800, 'services'],
  ['house-painting', 'a house painting job', '🎨', 4500, 'services'],
  ['funeral', 'a funeral', '⚱️', 9500, 'services'],
  ['childcare-year', 'a year of childcare', '🧸', 15000, 'services'],
  ['wedding-small', 'a small wedding', '💒', 30000, 'services'],

  // housing
  ['key-cut', 'a spare key cut', '🔑', 3.5, 'housing'],
  ['furnace-filter', 'a furnace filter', '🌬️', 14, 'housing'],
  ['renters-insurance-month', "a month of renter's insurance", '🏠', 18, 'housing'],
  ['smoke-alarm', 'a smoke alarm', '🚨', 22, 'housing'],
  ['door-lock', 'a door lock', '🔒', 32, 'housing'],
  ['water-month', 'a month of water', '🚰', 45, 'housing'],
  ['rental-application', 'a rental application fee', '📝', 55, 'housing'],
  ['gas-heating-month', 'a month of gas heating', '🔥', 95, 'housing'],
  ['storage-unit-month', 'a month of a storage unit', '📦', 130, 'housing'],
  ['electricity-month', 'a month of electricity', '⚡', 145, 'housing'],
  ['home-insurance-month', 'a month of home insurance', '🏠', 165, 'housing'],
  ['parking-space-month', 'a month of a parking space', '🅿️', 185, 'housing'],
  ['shared-room-week', 'a week in a shared room', '🛏️', 210, 'housing'],
  ['hoa-dues-month', 'a month of association dues', '🏘️', 290, 'housing'],
  ['property-tax-month', 'a month of property tax', '🏛️', 340, 'housing'],
  ['rent-studio', 'a month of rent on a studio', '🏠', 1250, 'housing'],
  ['rent-one-bed', 'a month of rent on a one-bedroom', '🏠', 1650, 'housing'],
  ['security-deposit', 'a security deposit', '🔑', 1800, 'housing'],
  ['home-insurance-year', 'a year of home insurance', '🏠', 1980, 'housing'],
  ['mortgage-month', 'a month of mortgage payments', '🏦', 2200, 'housing'],
  ['rent-family-home', 'a month of rent on a family home', '🏡', 2600, 'housing'],
  ['utilities-year', 'a year of utilities', '💡', 3600, 'housing'],
  ['rent-big-city', 'a month of rent in a big city', '🌆', 3800, 'housing'],
  ['property-tax-year', 'a year of property tax', '🏛️', 4100, 'housing'],
  ['rent-year-one-bed', 'a year of rent on a one-bedroom', '🏠', 19800, 'housing'],
  ['agent-commission', 'an estate agent commission', '🤝', 21000, 'housing'],
  ['house-deposit', 'a down payment on a house', '🏡', 48000, 'housing'],

  // health
  ['toothpaste', 'a tube of toothpaste', '🦷', 3.75, 'health'],
  ['plasters', 'a box of plasters', '🩹', 4.25, 'health'],
  ['toothbrush', 'a toothbrush', '🪥', 4.99, 'health'],
  ['painkillers', 'a bottle of painkillers', '💊', 6.5, 'health'],
  ['vitamins', 'a bottle of vitamins', '💊', 12, 'health'],
  ['reading-glasses', 'a pair of reading glasses', '👓', 18, 'health'],
  ['first-aid-kit', 'a first aid kit', '🧰', 24, 'health'],
  ['flu-shot', 'a flu shot', '💉', 35, 'health'],
  ['prescription-month', 'a month of a prescription', '💊', 45, 'health'],
  ['eye-test', 'an eye test', '👁️', 95, 'health'],
  ['physical-therapy', 'a physical therapy session', '🤸', 120, 'health'],
  ['dental-cleaning', 'a dental cleaning', '🦷', 145, 'health'],
  ['therapy-session', 'a therapy session', '🛋️', 165, 'health'],
  ['doctor-visit', "a doctor's visit", '🩺', 180, 'health'],
  ['blood-panel', 'a blood test panel', '🩸', 210, 'health'],
  ['dental-filling', 'a dental filling', '🦷', 240, 'health'],
  ['glasses-prescription', 'a pair of prescription glasses', '👓', 320, 'health'],
  ['contacts-year', 'a year of contact lenses', '👁️', 480, 'health'],
  ['health-insurance-month', 'a month of health insurance', '🏥', 560, 'health'],
  ['root-canal', 'a root canal', '🦷', 1400, 'health'],
  ['er-visit', 'an emergency room visit', '🚑', 2800, 'health'],
  ['trainer-year', 'a year with a personal trainer', '🏋️', 3600, 'health'],
  ['hearing-aids', 'a pair of hearing aids', '👂', 4500, 'health'],
  ['braces', 'a set of braces', '🦷', 6200, 'health'],
  ['health-insurance-year', 'a year of health insurance', '🏥', 6800, 'health'],
  ['hospital-stay', 'a hospital stay', '🏥', 14000, 'health'],
  ['surgery', 'a course of surgery', '🏥', 32000, 'health'],

  // travel
  ['luggage-tag', 'a luggage tag', '🏷️', 5.5, 'travel'],
  ['airport-coffee', 'an airport coffee', '☕', 6.75, 'travel'],
  ['travel-insurance-day', 'a day of travel insurance', '🛡️', 8.5, 'travel'],
  ['travel-adapter', 'a travel adapter', '🔌', 14, 'travel'],
  ['passport-photo', 'a passport photo', '📷', 16, 'travel'],
  ['checked-bag', 'a checked bag fee', '🧳', 40, 'travel'],
  ['hostel-night', 'a night in a hostel', '🛏️', 45, 'travel'],
  ['airport-transfer', 'an airport transfer', '🚐', 55, 'travel'],
  ['car-hire-day', 'a day of car hire', '🚗', 65, 'travel'],
  ['budget-hotel-night', 'a night in a budget hotel', '🏨', 110, 'travel'],
  ['suitcase', 'a suitcase', '🧳', 130, 'travel'],
  ['flight-domestic-one-way', 'a one-way domestic flight', '✈️', 180, 'travel'],
  ['hotel-night', 'a night in a nice hotel', '🏨', 280, 'travel'],
  ['flight-domestic-return', 'a return domestic flight', '✈️', 340, 'travel'],
  ['car-hire-week', 'a week of car hire', '🚗', 380, 'travel'],
  ['train-cross-country', 'a train across the country', '🚆', 420, 'travel'],
  ['hotel-luxury-night', 'a night in a luxury hotel', '🏨', 620, 'travel'],
  ['flight-lisbon', 'a return flight to lisbon', '✈️', 720, 'travel'],
  ['flight-tokyo', 'a return flight to tokyo', '✈️', 1400, 'travel'],
  ['beach-week', 'a week at the beach', '🏖️', 1800, 'travel'],
  ['ski-week', 'a week of skiing', '🎿', 2600, 'travel'],
  ['flight-business', 'a business class flight', '💺', 4200, 'travel'],
  ['holiday-two-weeks', 'a two-week holiday for two', '🌴', 6500, 'travel'],
  ['cruise-two', 'a cruise for two', '🚢', 8800, 'travel'],
  ['safari', 'a safari', '🦁', 9500, 'travel'],
  ['round-the-world', 'a round-the-world ticket', '🌍', 12000, 'travel'],
  ['travel-year', 'a year of travelling', '🎒', 38000, 'travel'],

  // education
  ['library-fine', 'a library late fee', '📚', 2.5, 'education'],
  ['notebook', 'a notebook', '📓', 3.25, 'education'],
  ['school-lunch', 'a school lunch', '🍱', 4.75, 'education'],
  ['pens-pack', 'a pack of pens', '🖊️', 5.5, 'education'],
  ['highlighters', 'a set of highlighters', '🖍️', 7.25, 'education'],
  ['pencil-case', 'a pencil case', '✏️', 8.5, 'education'],
  ['language-app-month', 'a month of a language app', '🗣️', 12, 'education'],
  ['textbook-used', 'a used textbook', '📗', 28, 'education'],
  ['online-course', 'an online course', '💻', 45, 'education'],
  ['music-lesson', 'a music lesson', '🎻', 65, 'education'],
  ['driving-lesson', 'a driving lesson', '🚗', 75, 'education'],
  ['school-uniform', 'a school uniform', '👔', 95, 'education'],
  ['textbook-new', 'a new textbook', '📘', 120, 'education'],
  ['school-supplies', 'a set of school supplies', '🎒', 140, 'education'],
  ['certification-exam', 'a certification exam', '📜', 340, 'education'],
  ['tutoring-month', 'a month of tutoring', '📖', 480, 'education'],
  ['textbooks-semester', 'a semester of textbooks', '📚', 620, 'education'],
  ['workshop-professional', 'a professional workshop', '📊', 750, 'education'],
  ['driving-school-year', 'a year of driving school', '🚦', 1600, 'education'],
  ['college-semester', 'a semester at community college', '🏫', 2400, 'education'],
  ['music-school-year', 'a year of music school', '🎼', 3200, 'education'],
  ['bootcamp', 'a coding bootcamp', '💻', 4500, 'education'],
  ['college-year', 'a year at community college', '🏫', 4800, 'education'],
  ['private-school-term', 'a term of private school', '🏫', 6800, 'education'],
  ['private-school-year', 'a year of private school', '🏫', 22000, 'education'],
  ['state-university-year', 'a year at a state university', '🎓', 28000, 'education'],
  ['private-university-year', 'a year at a private university', '🎓', 58000, 'education'],
];

/**
 * Every catalogue price is a typical US retail price, so the currency and the
 * source are properties of the list rather than of any entry. Storing them per
 * item would invite a typo that quietly mislabels one price as, say, EUR — and
 * a mislabelled currency is a silent 10-30% error in a converted answer, which
 * is exactly the confident-but-wrong failure the project refuses to ship.
 */
export const CATALOGUE: PracticeItem[] = ENTRIES.map(
  ([id, label, emoji, amount, category]) => ({
    id,
    label,
    emoji,
    amount,
    currency: 'USD',
    category,
    source: 'catalogue',
  }),
);
